[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.0",
    "html2text>=2025.4.15",
    "markdown>=3.9",
    "pillow>=11.3.0",
    "pygments>=2.19.2",
    "requests>=2.32.5",
]
